#pragma once

#define HTTP_SVR_NS_BEGIN namespace __http_svr_ns__ {
#define HTTP_SVR_NS_END }
#define USING_HTTP_SVR_NS using namespace __http_svr_ns__;

#define MAX_WEB_RECV_LEN            102400
#define MAX_ACCEPT_COUNT            256
enum CConnState
{
	CONN_IDLE,
	CONN_FATAL_ERROR,
	CONN_DATA_ERROR,
	CONN_CONNECTING,
	CONN_DISCONNECT,
	CONN_CONNECTED,
	CONN_DATA_SENDING,
	CONN_DATA_RECVING,
	CONN_SEND_DONE,
	CONN_RECV_DONE,
	CONN_APPEND_SENDING,
	CONN_APPEND_DONE,
	CONN_XML_POLICY
};

enum TDecodeStatus
{
	DECODE_FATAL_ERROR,
	DECODE_DATA_ERROR,
	DECODE_WAIT_HEAD,
	DECODE_WAIT_CONTENT,
	DECODE_HEAD_DONE,
	DECODE_CONTENT_DONE,
	DECODE_DONE,
	DECODE_DISCONNECT_BY_USER,
	DECODE_SAME_SERVER_REG = 8       //有相同类型Server用相同Serverid注册
};

enum ConnType
{
	CONN_CLINET,
	CONN_OTHER
};

